### ISSUE TITLE
Clearing the Hypothesis

### ISSUE THREAD

**Issue by TheGipsyTrail** [dimixar/Unity3DPocketSphinx-plugin#1]
Hi, @dimixar !
Thank you for your project! It made clear some issues of using pocketsphinx with Unity3D. However, there is one issue we didn't solve yet: 
every time we have to use _pocketSphinx.StopRecognizer(); and then _pocketSphinx.StartListening(searchKey) to clear the hypothesis. This slows down the application dramatically. Are there any possibilities to clear hypothesis without stopping the recognizer? Thank you!

**Comment by dimixar** [comment]
This repo is just a simple experiment. If you want to extend the functionality and optimize it, then I would suggest you to check out this repo also: https://github.com/dimixar/unity3DPocketSphinx-android-lib

This is the link to the source code of the plugin for Unity.

**Comment by dimixar** [comment]
I don't plan on doing any changes.:relaxed:

**Comment by tiancaipipi110** [comment]
@dimixar I opened the 'AndroidSpeechRecogDemo' scene and tested 'oh mighty computer' to wake up, nothing happened. Am I doing anything wrong?
